#!/bin/bash

cd $(dirname $0)

# symlinks all files and dirs starting with '.' into the home directory
for item in $(ls -a | grep '^\.' | grep -x -v '.\|..\|.DS_Store\|.git\|.gitignore'); do 
	src=$(pwd)/$item
	dest=~/$(echo $item)
	if [[ -L $dest ]]; then # delete $dest if it's already a symlink to somewhere
		rm $dest
	fi
	echo linking $item...
	ln -s $src $dest # this'll fail if $dest already exists 
done

# install standard brew packages
IFS=$'\n'
for i in $(cat brewlist.txt); do
    # brew "$i"
    if [[ $i != \#* ]] ; 
    then
        echo "$i" | xargs brew
    fi
done
